name: Generate HTML

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install the required dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Run the Python script to generate the HTML
      - name: Run script
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          set -e
          python script.py

      # Step 5: List the entire repository contents for debugging
      - name: List entire repository contents
        run: ls -la

      # Step 6: List the contents of the docs directory specifically
      - name: List docs directory contents
        run: ls -la docs/

      # Step 7: Set Git configuration
      - name: Set Git configuration
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Step 8: Commit changes to the docs/ directory
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update generated HTML [skip ci]'
          file_pattern: 'docs/**'
          github_token: ${{ secrets.GITHUB_TOKEN }}
