name: Generate HTML

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 * * * *'  # Runs every hour, adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run the Python script that generates HTML and images
      - name: Run script
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          python script.py

      # Ensure that Git is configured to commit changes
      - name: Set Git configuration
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Commit the changes in docs/ (including .nojekyll and HTML file)
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update generated HTML [skip ci]'
          file_pattern: 'docs/**'  # Broader pattern to include all files
          github_token: ${{ secrets.GITHUB_TOKEN }}
